language: ruby

install:
  - curl -u $RUBYGEMS_USER:$RUBYGEMS_PASSWORD https://rubygems.org/api/v1/api_key.yaml > ~/.gem/credentials
  - chmod 0600 ~/.gem/credentials

script:
  - gem build ./base_action.gemspec
  - gem push ./base_action-*.gem
